### ISSUE TITLE
bats setup fails to load when running itest

### ISSUE THREAD

**Issue by kief** [kudulab/docker-terraform-dojo#8]
Howdy!

When I run `./tasks build` and then `./tasks/itest`, I get the following error:

```
operations.bats
 ✗ setup_file failed
   (in test file test/integration/end_user/operations.bats, line 1)
     `load '/opt/bats-support/load.bash'' failed with status 0
   bats_load_safe: Could not find '/opt/bats-support/load.bash'[.bash]
   bats warning: Executed 1 instead of expected 13 tests

13 tests, 1 failure, 12 not run
```

It looks like the tests are expecting me to have the bats-support project cloned into my `/opt` folder, but I can't work out when and how this should have happened. The `itest` argument is going to run `time bats "$(pwd)/test/integration/end_user"`, this will be running on my host system, not inside the container instance, will it? In any case I don't see the bats-support files having been checked out into /opt on the image.

Clues appreciated!

**Comment by xmik** [comment]
Hi Kief!
Thanks for using docker-terraform-dojo and for creating this issue. Indeed, the tests are supposed to run on your host system. Having bats-core, bats-support and bats-assert set up is a prerequisite. 

I added a task that can be used to install these prerequisites automatically. You can just run it with `sudo ./tasks install_bats`. 

Another option is - follow the commands from the [tasks](https://github.com/kudulab/docker-terraform-dojo/blob/1.6.2/tasks#L69) file by yourself. 

Another (3rd) option would be to run the tests in a docker container using [docker-inception-dojo docker image](https://github.com/kudulab/docker-inception-dojo). You'd have to:
1. Create a Dojofile e.g.
```
$ cat Dojofile.dind
DOJO_DOCKER_IMAGE="kudulab/inception-dojo:ubuntu18-dind-0.3.0"
DOJO_DOCKER_OPTIONS=--privileged
```
2. Create a container from that inception dojo docker image: `dojo -c Dojofile.dind`
3. Install the bats frameworks there in the container: `sudo ./tasks install_bats`
4. Run the tests: `./tasks itest`

Let me know how it goes and how we could improve this process :)
